import { standardEditionId, type BiblicalSubject, type CardDefinition, type CardEdition, type CollectionDefinition } from '@/domain/cards';
import type { EditorialMeta } from '@/domain/content';

/**
 * Kingdom Discovery — Series I (prototype set).
 *
 * All summaries are DRAFT copy awaiting biblical editorial review, and all
 * artwork is temporary procedural art (see docs/CONTENT_GUIDELINES.md).
 * Card ids are permanent once published; never rename or reuse them.
 */
const DRAFT: EditorialMeta = { status: 'draft', revision: 1, placeholderArt: true };

export const SUBJECTS: readonly BiblicalSubject[] = [
  { id: 'noah', name: 'Noah', kind: 'person' },
  { id: 'moses', name: 'Moses', kind: 'person' },
  { id: 'joshua', name: 'Joshua', kind: 'person' },
  { id: 'ruth', name: 'Ruth', kind: 'person' },
  { id: 'david', name: 'David', kind: 'person' },
  { id: 'davids-sling', name: 'David’s Sling', kind: 'artifact' },
  { id: 'elijah', name: 'Elijah', kind: 'person' },
  { id: 'daniel', name: 'Daniel', kind: 'person' },
  { id: 'esther', name: 'Esther', kind: 'person' },
];

export const COLLECTION_ID = 'kingdom-discovery-s1';

export const CARDS: readonly CardDefinition[] = [
  {
    id: 'noah-covenant',
    subjectId: 'noah',
    collectionId: COLLECTION_ID,
    collectorNumber: 1,
    title: 'Noah',
    epithet: 'The Covenant Rainbow',
    category: 'heroes',
    rarity: 'rare',
    passage: { book: 'GEN', chapter: 9 },
    keyVerse: { book: 'GEN', chapter: 9, verseStart: 13 },
    summary: 'After the flood, God set His rainbow in the clouds as the sign of His covenant with the earth.',
    themes: ['Obedience', 'Hope'],
    artKey: 'noah',
    editorial: DRAFT,
  },
  {
    id: 'moses-sea',
    subjectId: 'moses',
    collectionId: COLLECTION_ID,
    collectorNumber: 2,
    title: 'Moses',
    epithet: 'The Sea Divided',
    category: 'miracles',
    rarity: 'epic',
    passage: { book: 'EXO', chapter: 14 },
    keyVerse: { book: 'EXO', chapter: 14, verseStart: 21, verseEnd: 22 },
    summary: 'Moses stretched out his hand over the sea, and the LORD divided the waters so Israel crossed on dry ground.',
    themes: ['Faith', 'Deliverance'],
    artKey: 'moses',
    editorial: DRAFT,
  },
  {
    id: 'joshua-courage',
    subjectId: 'joshua',
    collectionId: COLLECTION_ID,
    collectorNumber: 3,
    title: 'Joshua',
    epithet: 'Strong and Courageous',
    category: 'heroes',
    rarity: 'rare',
    passage: { book: 'JOS', chapter: 1 },
    keyVerse: { book: 'JOS', chapter: 1, verseStart: 9 },
    summary: 'As Joshua prepared to lead Israel into the promised land, God told him to be strong and courageous.',
    themes: ['Courage', 'Obedience'],
    artKey: 'joshua',
    editorial: DRAFT,
  },
  {
    id: 'ruth-loyal',
    subjectId: 'ruth',
    collectionId: COLLECTION_ID,
    collectorNumber: 4,
    title: 'Ruth',
    epithet: 'Where You Go',
    category: 'women_of_faith',
    rarity: 'common',
    passage: { book: 'RUT', chapter: 1 },
    keyVerse: { book: 'RUT', chapter: 1, verseStart: 16 },
    summary: 'Ruth refused to leave her mother-in-law Naomi, choosing Naomi’s people and Naomi’s God as her own.',
    themes: ['Loyalty', 'Kindness'],
    artKey: 'ruth',
    editorial: DRAFT,
  },
  {
    id: 'david-shepherd',
    subjectId: 'david',
    collectionId: COLLECTION_ID,
    collectorNumber: 5,
    title: 'David',
    epithet: 'The Shepherd',
    category: 'heroes',
    rarity: 'common',
    passage: { book: '1SA', chapter: 16 },
    keyVerse: { book: '1SA', chapter: 16, verseStart: 7 },
    summary: 'Jesse’s youngest son was tending the sheep when Samuel anointed him, for the LORD looks at the heart.',
    themes: ['Humility', 'Faithfulness'],
    artKey: 'david-shepherd',
    editorial: DRAFT,
  },
  {
    id: 'david-giant-slayer',
    subjectId: 'david',
    collectionId: COLLECTION_ID,
    collectorNumber: 6,
    title: 'David',
    epithet: 'The Giant Slayer',
    category: 'heroes',
    rarity: 'legendary',
    passage: { book: '1SA', chapter: 17 },
    keyVerse: { book: '1SA', chapter: 17, verseStart: 45 },
    summary: 'A shepherd who trusted God faced the giant Goliath with a sling and a stone.',
    themes: ['Courage', 'Faith', 'Trust'],
    artKey: 'david-giant-slayer',
    relatedQuestId: 'valley-of-elah',
    editorial: DRAFT,
  },
  {
    id: 'sling-and-stones',
    subjectId: 'davids-sling',
    collectionId: COLLECTION_ID,
    collectorNumber: 7,
    title: 'Sling & Stones',
    epithet: 'Five Smooth Stones',
    category: 'artifacts',
    rarity: 'rare',
    passage: { book: '1SA', chapter: 17 },
    keyVerse: { book: '1SA', chapter: 17, verseStart: 40 },
    summary: 'David chose five smooth stones from the brook and went out to meet Goliath with his sling in hand.',
    themes: ['Preparation', 'Trust'],
    artKey: 'sling-stones',
    relatedQuestId: 'valley-of-elah',
    editorial: DRAFT,
  },
  {
    id: 'david-king',
    subjectId: 'david',
    collectionId: COLLECTION_ID,
    collectorNumber: 8,
    title: 'David',
    epithet: 'The King',
    category: 'heroes',
    rarity: 'rare',
    passage: { book: '2SA', chapter: 5 },
    keyVerse: { book: '2SA', chapter: 5, verseStart: 3, verseEnd: 4 },
    summary: 'The elders of Israel anointed David king at Hebron, and he reigned forty years.',
    themes: ['Leadership', 'Covenant'],
    artKey: 'david-king',
    editorial: DRAFT,
  },
  {
    id: 'david-psalmist',
    subjectId: 'david',
    collectionId: COLLECTION_ID,
    collectorNumber: 9,
    title: 'David',
    epithet: 'The Psalmist',
    category: 'scripture',
    rarity: 'epic',
    passage: { book: 'PSA', chapter: 23 },
    keyVerse: { book: 'PSA', chapter: 23, verseStart: 1 },
    summary: 'Many psalms are titled as psalms of David, including Psalm 23: “The LORD is my shepherd.”',
    themes: ['Worship', 'Trust'],
    artKey: 'david-psalmist',
    editorial: DRAFT,
  },
  {
    id: 'elijah-fire',
    subjectId: 'elijah',
    collectionId: COLLECTION_ID,
    collectorNumber: 10,
    title: 'Elijah',
    epithet: 'Fire on Carmel',
    category: 'miracles',
    rarity: 'common',
    passage: { book: '1KI', chapter: 18 },
    keyVerse: { book: '1KI', chapter: 18, verseStart: 38 },
    summary: 'On Mount Carmel, Elijah prayed and the fire of the LORD fell, showing Israel that the LORD is God.',
    themes: ['Boldness', 'Prayer'],
    artKey: 'elijah',
    editorial: DRAFT,
  },
  {
    id: 'daniel-lions',
    subjectId: 'daniel',
    collectionId: COLLECTION_ID,
    collectorNumber: 11,
    title: 'Daniel',
    epithet: 'The Lions’ Den',
    category: 'heroes',
    rarity: 'rare',
    passage: { book: 'DAN', chapter: 6 },
    keyVerse: { book: 'DAN', chapter: 6, verseStart: 22 },
    summary: 'Daniel kept praying despite the king’s decree, and God shut the mouths of the lions.',
    themes: ['Faithfulness', 'Integrity'],
    artKey: 'daniel',
    editorial: DRAFT,
  },
  {
    id: 'esther-courage',
    subjectId: 'esther',
    collectionId: COLLECTION_ID,
    collectorNumber: 12,
    title: 'Esther',
    epithet: 'For Such a Time',
    category: 'women_of_faith',
    rarity: 'epic',
    passage: { book: 'EST', chapter: 4 },
    keyVerse: { book: 'EST', chapter: 4, verseStart: 14 },
    summary: 'Esther risked her life to approach the king on behalf of her people, “for such a time as this.”',
    themes: ['Courage', 'Providence'],
    artKey: 'esther',
    editorial: DRAFT,
  },
];

/** Milestone 1 ships one standard edition per card. Cosmetic editions arrive later. */
export const EDITIONS: readonly CardEdition[] = CARDS.map((card) => ({
  id: standardEditionId(card.id),
  cardId: card.id,
  kind: 'standard',
  name: 'Standard Edition',
}));

export const COLLECTIONS: readonly CollectionDefinition[] = [
  {
    id: COLLECTION_ID,
    name: 'Kingdom Discovery',
    series: 'Series I · Prototype',
    cardIds: CARDS.map((card) => card.id),
  },
];
